# Generated by Django 5.2.8 on 2025-11-25 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('has_diabetes', models.BooleanField(blank=True, null=True)),
                ('had_corona', models.BooleanField(blank=True, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=50)),
                ('blood_category', models.CharField(blank=True, max_length=10)),
                ('question_7', models.TextField(blank=True)),
                ('question_8', models.TextField(blank=True)),
                ('question_9', models.TextField(blank=True)),
                ('question_10', models.TextField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
