# Generated by Django 5.2.8 on 2025-11-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhealthprofile',
            name='allergies_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userhealthprofile',
            name='chronic_diseases_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userhealthprofile',
            name='donated_before',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userhealthprofile',
            name='eligibility_reasons',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userhealthprofile',
            name='eligibility_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userhealthprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userhealthprofile',
            name='has_allergies',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userhealthprofile',
            name='has_anemia',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userhealthprofile',
            name='has_chronic_diseases',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userhealthprofile',
            name='has_infectious_disease',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userhealthprofile',
            name='has_surgery_recently',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userhealthprofile',
            name='has_tattoo_piercing',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userhealthprofile',
            name='hemoglobin_level',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userhealthprofile',
            name='infectious_disease_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userhealthprofile',
            name='is_breastfeeding',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userhealthprofile',
            name='is_pregnant',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userhealthprofile',
            name='last_donation_date',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userhealthprofile',
            name='medications_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userhealthprofile',
            name='surgery_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userhealthprofile',
            name='taking_medications',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userhealthprofile',
            name='tattoo_piercing_date',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userhealthprofile',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
